### ISSUE TITLE
Request for help with Ginnie Mae (or GSE) loan data

### ISSUE THREAD

**Issue by baridhi** [toddwschneider/agency-loan-level#3]
Hi Todd,

Glad to come across some detailed work in your repository here. I'm a PhD student and I came across your Github repository while searching for Fannie/Ginnie Mae data. I'm interested to get specific info about bonds issued against some housing MBS. Please see the file attached. I was wondering if you could guide/help me in collecting/understanding the loan level data about the underlying securities mentioned in pages 3 onwards (with CUSIP and pool # etc.). To be very precise: I'm looking to create a dataset which has individual loans (anonymous, I guess) which go into specific California bond securities (based on the disclosure pdf). I'm not sure where to start and how best to merge. Clearly, this is not an "issue" - but a request for help. Unfortunately, I couldn't find any other channel to float this. Happy to be redirected adequately.
[California_eg_ER846035-ER660692-ER1062467.pdf](https://github.com/toddwschneider/agency-loan-level/files/5740066/California_eg_ER846035-ER660692-ER1062467.pdf)

**Comment by toddwschneider** [comment]
Hi @baridhi I responded to you via email so am going to close this issue here. Thanks
